### ISSUE TITLE
Keyboard Type - Number

### ISSUE THREAD

**Issue by kkrishnan90** [VictorRancesCode/json_to_form#7]
Thanks for this wonderful flutter package. I wonder if there is a way tor restrict the keyboard input type to numbers for entering mobile number details in an input form. Could you guide me on how to set it up?

**Comment by maniecodes** [comment]
> Thanks for this wonderful flutter package. I wonder if there is a way tor restrict the keyboard input type to numbers for entering mobile number details in an input form. Could you guide me on how to set it up?

In the 
Textform field(
      keyboardType: TextInputType.number,
 )

**Comment by H-ishak** [comment]
@VictorRancesCode  i sent you an email about this feature please check your email.
